const cardData = [
  {
    id: "CW",
    title: "COMMERCIAL WEBSITE",
    price: "£1500",
    estimate: "4 weeks or less",
    bPoints1: [
      "5-page static website – Custom-designed for your industry (£1500 one-time fee)",
      "+£150 per extra page – Scale up as needed",
      "Your choice of build – Coded (recommended for best results) or no-code",
      "Mobile-optimized & SEO-ready – Looks great and performs better",
    ],
    bPoints2: [
      "Dynamic websites – Not suitable for e-commerce, user accounts, or complex functionality",
      "Hosting & domain – You’ll need to arrange these separately (I can recommend free/paid options)",
      "Ongoing updates – unless you opt for my website management plan",
    ],
    bPoints3: [
      "Startups testing their idea",
      "Freelancers & solopreneurs",
      "Small businesses",
      "Artists/creatives with tight budgets",
    ],
    tagLine: "Your affordable launchpad.",
    desc: [
      `This service is perfect for small businesses, freelancers, and startups who need a straightforward, professional website to establish their online presence. For a one-time fee of £1500, you'll receive a custom-designed, static 5-page website tailored to your specific industry or business needs. Need more pages? Additional pages are available at £150 each. While I typically recommend custom-coded websites for optimal results, I also offer no-code solutions if that better suits your requirements.`,
      `Think of this as your affordable launchpad – a clean, professional website that lets you test your business concept online with minimal investment. When you're ready to grow, we can discuss more advanced solutions.`,
      `Please note this service is designed for static websites only – it's not suitable for dynamic sites like e-commerce platforms or member-based websites. You'll be responsible for arranging your own hosting and domain (though I'm happy to provide recommendations, including free hosting options for hard-coded sites).`,
    ],
    artSrc: "CW.svg",
    gridBgColor: "var(--bh-light)",
    textColor: "var(--brutal-dark)",
  },
  {
    id: "CP",
    title: "CREATIVE PROJECT",
    price: "Tailored quote",
    estimate: "6+ weeks",
    bPoints1: [
      "100% custom design – Zero templates; built from scratch to your vision",
      "Cutting-edge tech – 3D animation, motion graphics, and interactive storytelling",
      "High-performance code – Blazing-fast, SEO-optimized, and scalable",
      "Headless CMS options – For content updates without design limits",
      "White-glove collaboration – Your input shapes every stage",
    ],
    bPoints2: [
      "No-code solutions – the service can only be achieved with custom code",
      "Off-the-shelf templates or themes – this is all about what makes you unique",
      "Basic brochure sites – this is for transformative work",
    ],
    bPoints3: [
      "Creative studios",
      "Luxury brands",
      "Innovators",
      "Agencies",
      "Disruptors",
    ],
    tagLine: "Your digital flagship, uncompromised.",
    desc: [
      "This is for visionaries who refuse to be confined by templates or conventional solutions. Through a fully collaborative process, we’ll harness cutting-edge technologies—from immersive 3D animation to precision-engineered interactive design—to create a website that doesn’t just meet expectations, but dismantles them. Every pixel, interaction, and line of code will be custom-crafted to reflect what makes your brand or creative practice singular.",
      "While no-code solutions can’t deliver this level of artistry and performance, we can integrate a headless CMS if you need to manage content updates without compromising the bespoke experience. Ideal for artists, innovators, and brands who see their website as a dynamic flagship—not just a digital placeholder.",
    ],
    artSrc: "CP.svg",
    gridBgColor: "var(--bh-red)",
    textColor: "var(--bh-light)",
  },
  {
    id: "CC",
    title: "Website Management",
    price: "£99/month",
    estimate: "4 weeks or less",
    bPoints1: [
      "5-page website (worth £1500) – Built to your specs",
      "Unlimited content updates – Keep your site fresh",
      "Hosting & security – Fully managed",
      "Office-hour support – Fast help when you need it",
      "No long-term lock-in – Cancel after 6 months",
    ],
    bPoints2: [
      "Major redesigns or structural changes – but we can discuss upgrades",
      "24/7 emergency support – but I'm always available within office hours",
      "Custom development beyond standard updates – for a more complex website take a look at my Creative Project service",
    ],
    bPoints3: [
      "Small businesses who want a hands-off website",
      "Startups needing a low-commitment way to launch",
      "Freelancers who want to focus on clients, not tech",
      "Anyone tired of dealing with web designers who disappear after launch",
    ],
    tagLine: "Your Website, Always Covered – For Less Than £100/Month.",
    desc: [
      "For just £99 per month (with a 6-month minimum commitment), this comprehensive service provides everything you need to maintain a professional online presence without the typical headaches. You'll receive a brand new 5-page website worth £1500, complete with unlimited content updates whenever you need to refresh text, images, or pages. I'll handle all the technical aspects including hosting and security, while providing reliable support during office hours for any questions or adjustments. After the initial six months, you're free to continue or cancel at any time.",
      "This solution is ideal for businesses that want to focus on their work rather than website maintenance. Whether you're a startup looking for a low-risk way to establish your online presence, a small business owner tired of dealing with technical issues, or a creative professional who'd rather spend time on clients than content updates, this service acts as your invisible website partner. You get all the benefits of having an expert on call, without the complexity or unpredictable costs of traditional web maintenance.",
    ],
    artSrc: "CC.svg",
    gridBgColor: "var(--brutal-dark)",
    textColor: "var(--brutal-light)",
  },
];

export default cardData;
